### ISSUE TITLE
Roldan Uriel Arcadio Avila 4BS infografia 

### ISSUE THREAD

**Issue by roldanU** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-roldanU#1]
[Roldan uriel Arcadio Avila 4BS infografia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-roldanU/files/14566568/Roldan.uriel.Arcadio.Avila.4BS.infografia.pdf)

**Comment by josealfredo79** [comment]
@roldanU Falta la calificación...

**Comment by josealfredo79** [comment]
Bien echo y revisado..
